name: capo
description: RChain Mobile Wallet

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:

  #store
  shared_preferences: ^0.5.4+1
  #localization
  easy_localization: 1.4.0+2
  flutter_localizations:
    sdk: flutter
  #qrcode
  barcode_scan: 2.0.1
  qr_flutter: 3.2.0
  image_picker: 0.6.3+4
  r_scan: 0.1.4+1
  permission_handler: 4.4.0
  # version update
  package_info: ^0.4.0+18
  flutter_xupdate: 0.0.4
  # State
  provider: ^3.1.0+1

  hex: 0.1.2
  oktoast: ^2.2.0+1
  rxdart: 0.23.1
  flutter_section_table_view: 1.0.5
  dio: 3.0.10
  dio_http_cache: 0.2.6
  flutter_markdown: 0.3.4
  decimal: ^0.3.0
  version: 1.0.3
  url_launcher: 5.4.2

#google
  firebase_analytics: 5.0.11
  firebase_core:  0.4.4+3

#github
  capo_core_dart:
    git: https://github.com/matteozero/Capo_Core_Dart.git

  rxbus:
    git: https://github.com/imphila/FlutterRxBus.git


dev_dependencies:
  flutter_test:
    sdk: flutter

  ff_annotation_route:
    git: https://github.com/imphila/ff_annotation_route.git
#    path: /Users/matteo/Dev/Capo/packages/ff_annotation_route




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/langs/en-US.json
    - resources/langs/zh-CN.json
    - resources/images/common/
    - resources/images/app_icon/
    - resources/images/background/
    - lib/modules/settings/home/model/sections.json
    - lib/modules/settings/settings_modules/node_settings/view/readonly/model/readonly_sections.json
    - lib/modules/settings/settings_modules/node_settings/view/validator/model/validator_sections.json





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  fonts:
    - family: Karla
      fonts:
        - asset: resources/fonts/Karla/Karla-Bold.ttf
          weight: 700
        - asset: resources/fonts/Karla/Karla-BoldItalic.ttf
        - asset: resources/fonts/Karla/Karla-Italic.ttf
        - asset: resources/fonts/Karla/Karla-Regular.ttf
    - family: iconfont
      fonts:
        - asset: resources/fonts/iconfont/iconfont.ttf


